# Generated by Django 4.0.4 on 2022-04-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0002_alter_food_description_alter_food_fname_and_more'),
        ('UserApp', '0003_remove_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_food.food'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfooddetail',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.cart'),
        ),
        migrations.AlterField(
            model_name='userfooddetail',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_food.food'),
        ),
        migrations.AlterField(
            model_name='userfooddetail',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userfooddetail',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.status'),
        ),
        migrations.AlterField(
            model_name='userfooddetail',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
