# Generated by Django 4.0.4 on 2022-04-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0003_alter_food_price'),
        ('UserApp', '0005_alter_cart_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_food.food'),
        ),
    ]
