# Generated by Django 4.0.4 on 2022-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_cart_fid_alter_cart_quantity_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fid',
            new_name='fid_id',
        ),
    ]
