# Generated by Django 4.0.4 on 2022-04-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_rename_fid_cart_fid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fid_id',
            new_name='food',
        ),
    ]
