# Generated by Django 4.0.4 on 2022-04-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_rename_fid_id_cart_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='fid',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='userfooddetail',
            old_name='fid',
            new_name='food',
        ),
    ]
