# Generated by Django 4.0.4 on 2022-04-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
