# Generated by Django 4.0.4 on 2022-04-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0002_alter_food_description_alter_food_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(),
        ),
    ]
