# Generated by Django 4.0.4 on 2022-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_food', '0004_alter_food_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removefood',
            old_name='fid',
            new_name='food',
        ),
    ]
